//! `research/FINDINGS.md`, generated from `research/` itself.
//!
//! # Why this exists
//!
//! The corpus preserves its own wrong answers on purpose — AGENTS.md §5: *"When a conclusion is
//! retracted, the retraction sits next to the claim. Do not tidy away a wrong answer; the wrong
//! answer is how the next person avoids it."* That rule is right and this does not change it.
//!
//! What it costs is that **a reader cannot tell a live answer from a dead one by looking at it**.
//! Measured the day this was written: 845 headings across 17 documents, 93 retraction markers in
//! one file alone, and **not one document carrying a dated status**. `research/03` §22 states a
//! conclusion, §24 is headed `⚠️ RETRACTED`, and §25 gives the real answer — so §22 reads as
//! current to anyone who lands on it, which is exactly what happened during the click-wheel work
//! on 2026-09-01 and cost most of a session.
//!
//! §5 also says *"do not route discovery through an index; grep the directory"*, and that was
//! right about the index it was written against — a hand-maintained one, which does not drift
//! slowly, it stops. This index is generated from the files it describes and regenerated by a test
//! that fails on drift, so it cannot say something the corpus does not.
//!
//! # The convention, which was already there
//!
//! Nothing here asks the corpus to be rewritten. These markers are the ones the research already
//! uses, counted across its headings:
//!
//! | marker | meaning | count when adopted |
//! |---|---|---|
//! | `✅` | settled — the finding held | 14 |
//! | `⚠️` | corrected — the claim below it was wrong | 7 |
//! | `~~struck~~` | the struck text is the retracted claim | 10 |
//! | `RETRACTED` | the same, spelled out | 5 |
//! | `YYYY-MM-DD` | when it was measured | 36 |
//!
//! A heading with none of them is **unmarked**, which is a statement about the heading and not a
//! judgement of it: most prose is neither a finding nor a retraction.
//!
//! # The mechanism
//!
//! [`write_if_changed`] rewrites the file **and then panics**. A passing `cargo test` therefore
//! means the committed file matches what the corpus says, and a failing one leaves the correct file
//! on disk to commit. The generator is never a thing anybody has to remember to run. This is the
//! shape `arfi`'s `docs.rs` uses and `clickwheel/crates/docgen` uses before it; it is that pattern
//! restated here, for this corpus, in this repository's own terms.

use std::fmt::Write as _;
use std::path::Path;

/// What a heading says about the claim under it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    /// `✅` — measured and it held.
    Settled,
    /// `RETRACTED`, or a struck-through claim. The answer moved.
    Retracted,
    /// `⚠️` — something below this was wrong, and this says what.
    Corrected,
    /// Neither. Most headings, and not a criticism of them.
    Plain,
}

impl State {
    pub fn mark(self) -> &'static str {
        match self {
            State::Settled => "settled",
            State::Retracted => "RETRACTED",
            State::Corrected => "corrected",
            State::Plain => "",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Heading {
    pub level: usize,
    /// The heading with its markers and leading `#`s removed — what it actually says.
    pub text: String,
    pub line: usize,
    pub state: State,
    /// `YYYY-MM-DD`, if the heading carries one.
    pub date: Option<String>,
}

/// The first `YYYY-MM-DD` in a string, without a regex crate.
///
/// Bounded to a plausible range rather than any eight digits, so a hex dump or an address does not
/// read as a date — `0x20260901` would otherwise match on a corpus full of addresses.
fn find_date(s: &str) -> Option<String> {
    let b = s.as_bytes();
    if b.len() < 10 {
        return None;
    }
    // **Byte indices, not `&s[i..i + 10]`.** The corpus is full of em-dashes and section signs, and
    // slicing a `&str` at an arbitrary byte offset panics the moment a window starts inside one —
    // which it did, on `App Store — reassessed 2026-08-11`, the first heading that had one.
    let digit = |c: &u8| c.is_ascii_digit();
    for i in 0..=b.len() - 10 {
        let w = &b[i..i + 10];
        if !(w[0..4].iter().all(digit)
            && w[4] == b'-'
            && w[5..7].iter().all(digit)
            && w[7] == b'-'
            && w[8..10].iter().all(digit))
        {
            continue;
        }
        // Not part of a longer run of digits: `12026-08-11` is not a date, and neither is a date
        // with a digit glued to its end.
        if i > 0 && b[i - 1].is_ascii_digit() {
            continue;
        }
        if b.get(i + 10).is_some_and(|c| c.is_ascii_digit()) {
            continue;
        }
        // Every byte in the window is ASCII, so this is a valid `str` by construction.
        let t = std::str::from_utf8(w).ok()?;
        let (y, m, d): (u32, u32, u32) =
            (t[0..4].parse().ok()?, t[5..7].parse().ok()?, t[8..10].parse().ok()?);
        if (2000..=2100).contains(&y) && (1..=12).contains(&m) && (1..=31).contains(&d) {
            return Some(t.to_string());
        }
    }
    None
}

/// Read one document's headings.
pub fn headings(body: &str) -> Vec<Heading> {
    let mut out = Vec::new();
    let mut fenced = false;
    for (i, raw) in body.lines().enumerate() {
        // A `#` inside a fenced block is a shell comment or an assembly comment, not a heading.
        // Without this the corpus's own recipes — which are full of them — become findings.
        if raw.trim_start().starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if fenced || !raw.starts_with("##") {
            continue;
        }
        let level = raw.chars().take_while(|c| *c == '#').count();
        let text = raw[level..].trim();
        if text.is_empty() {
            continue;
        }
        let state = if text.contains("RETRACTED") || text.contains("~~") {
            State::Retracted
        } else if text.contains('⚠') {
            State::Corrected
        } else if text.contains('✅') {
            State::Settled
        } else {
            State::Plain
        };
        let clean = text
            .replace("✅", "")
            .replace("⚠️", "")
            .replace('⚠', "")
            .replace("~~", "")
            .trim()
            .to_string();
        out.push(Heading {
            level,
            date: find_date(&clean),
            text: clean,
            line: i + 1,
            state,
        });
    }
    out
}

/// One document, parsed.
pub struct Doc {
    pub name: String,
    pub headings: Vec<Heading>,
}

impl Doc {
    /// The newest dated heading — **where this document currently stands.**
    ///
    /// The single most useful line in the whole index. A document that grows by addendum puts its
    /// current answer at the bottom and its superseded ones above, and nothing on the page says so.
    pub fn newest(&self) -> Option<&Heading> {
        self.headings
            .iter()
            .filter(|h| h.date.is_some())
            .max_by(|a, b| a.date.cmp(&b.date).then(a.line.cmp(&b.line)))
    }

    pub fn count(&self, s: State) -> usize {
        self.headings.iter().filter(|h| h.state == s).count()
    }
}

/// Read every `NN-*.md` in a research directory, in filename order.
pub fn read_dir(dir: &Path) -> Vec<Doc> {
    let mut names: Vec<_> = std::fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .filter(|n| n.ends_with(".md") && n != "FINDINGS.md")
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    names.sort();
    names
        .into_iter()
        .filter_map(|name| {
            let body = std::fs::read_to_string(dir.join(&name)).ok()?;
            Some(Doc {
                headings: headings(&body),
                name,
            })
        })
        .collect()
}

/// Render the index.
pub fn render(docs: &[Doc]) -> String {
    let mut o = String::new();
    let total: usize = docs.iter().map(|d| d.headings.len()).sum();
    let dated: usize = docs
        .iter()
        .map(|d| d.headings.iter().filter(|h| h.date.is_some()).count())
        .sum();
    let by = |s: State| -> usize { docs.iter().map(|d| d.count(s)).sum() };

    o.push_str("# Findings — where each document stands\n\n");
    o.push_str(
        "<!-- GENERATED by `cargo run -p docgen`. Do not edit: edit the research and regenerate.\n\
         \x20    `cargo test -p docgen` fails if this file and the corpus disagree. -->\n\n",
    );
    o.push_str(
        "The corpus keeps its wrong answers on purpose (AGENTS.md §5) and this does not change\n\
         that. What it adds is a way to tell a live answer from a dead one **without reading the\n\
         whole file** — because a document that grows by addendum puts its current answer at the\n\
         bottom, and nothing on the page says so.\n\n",
    );
    let _ = writeln!(
        o,
        "{} headings across {} documents — {} dated, {} settled, {} retracted, {} corrected.\n",
        total,
        docs.len(),
        dated,
        by(State::Settled),
        by(State::Retracted),
        by(State::Corrected)
    );

    o.push_str("## Where each document stands today\n\n");
    o.push_str(
        "The newest dated heading in each file. **This is the answer that is current**; anything\n\
         above it in the same document may have been superseded.\n\n",
    );
    o.push_str("| document | newest dated finding | when | state |\n|---|---|---|---|\n");
    for d in docs {
        match d.newest() {
            Some(h) => {
                let _ = writeln!(
                    o,
                    "| [`{}`]({}) | {} | `{}` | {} |",
                    d.name,
                    d.name,
                    trim(&h.text, 74),
                    h.date.as_deref().unwrap_or(""),
                    h.state.mark()
                );
            }
            None => {
                let _ = writeln!(
                    o,
                    "| [`{}`]({}) | *nothing in it is dated* | — | |",
                    d.name, d.name
                );
            }
        }
    }

    o.push_str("\n## Retracted, and what came after it\n\n");
    o.push_str(
        "Every retracted or corrected heading, with the next dated heading in the same document.\n\
         **A retraction whose successor column is empty is a dead end** — the claim was withdrawn\n\
         and nothing dated replaced it.\n\n",
    );
    o.push_str("| document | withdrawn | line | what follows |\n|---|---|---|---|\n");
    let mut any = false;
    for d in docs {
        for (i, h) in d.headings.iter().enumerate() {
            if !matches!(h.state, State::Retracted | State::Corrected) {
                continue;
            }
            any = true;
            let next = d.headings[i + 1..]
                .iter()
                .find(|n| n.date.is_some())
                .map(|n| format!("{} `{}`", trim(&n.text, 46), n.date.as_deref().unwrap_or("")))
                .unwrap_or_else(|| "—".into());
            let _ = writeln!(
                o,
                "| `{}` | {} | {} | {} |",
                d.name,
                trim(&h.text, 52),
                h.line,
                next
            );
        }
    }
    if !any {
        o.push_str("| — | *nothing is marked retracted* | | |\n");
    }

    o.push_str("\n## Every document, in order\n\n");
    for d in docs {
        let _ = writeln!(o, "### [`{}`]({})\n", d.name, d.name);
        let marked: Vec<&Heading> = d
            .headings
            .iter()
            .filter(|h| h.state != State::Plain || h.date.is_some())
            .collect();
        if marked.is_empty() {
            let _ = writeln!(
                o,
                "{} headings, none of them marked or dated.\n",
                d.headings.len()
            );
            continue;
        }
        let _ = writeln!(
            o,
            "{} headings, {} of them marked or dated:\n",
            d.headings.len(),
            marked.len()
        );
        o.push_str("| line | when | state | heading |\n|---|---|---|---|\n");
        for h in marked {
            let _ = writeln!(
                o,
                "| {} | {} | {} | {} |",
                h.line,
                h.date.as_deref().unwrap_or("—"),
                h.state.mark(),
                trim(&h.text, 86)
            );
        }
        o.push('\n');
    }
    o
}

/// Shorten for a table cell, and neutralise the pipe so a heading cannot break the row.
fn trim(s: &str, n: usize) -> String {
    let s = s.replace('|', "\\|");
    if s.chars().count() <= n {
        return s;
    }
    let cut: String = s.chars().take(n - 1).collect();
    format!("{}…", cut.trim_end())
}

/// Write `want` to `path` if it differs, then **panic**.
///
/// 🔴 The panic is the point, and it is borrowed rather than invented — `arfi`'s `docs.rs` argues
/// it best: *"a generator that silently rewrites turns an uncommitted regeneration into a clean
/// local test run and a dirty tree somebody else discovers; failing makes drift arrive as a red
/// test, at the moment it is introduced, with the fix already applied on disk."*
pub fn write_if_changed(path: &Path, want: &str) {
    let have = std::fs::read_to_string(path).unwrap_or_default();
    if have == want {
        return;
    }
    std::fs::write(path, want).expect("write the regenerated index");
    panic!(
        "{} was out of date and has been rewritten. Commit it.\n\
         (This is a generator, not a checker — the correct file is now on disk.)",
        path.display()
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A date is a date, and an address is not.
    ///
    /// **The corpus is full of hex.** `0x20260901` has eight digits in the right order, and a naive
    /// eight-digit scan turns every such address into a finding's timestamp. The range check is what
    /// separates them, and this is the test that says so.
    #[test]
    fn a_date_is_recognised_and_an_address_is_not() {
        assert_eq!(find_date("Settled 2026-08-11 — the 5G").as_deref(), Some("2026-08-11"));
        assert_eq!(find_date("the redraw (2026-08-30)").as_deref(), Some("2026-08-30"));
        assert_eq!(find_date("at 0x20260901 the loader"), None);
        assert_eq!(find_date("§22 error 0x58"), None);
        assert_eq!(find_date("month 2026-13-01 does not exist"), None);
        assert_eq!(find_date("day 2026-08-99 does not exist"), None);
    }

    /// The markers the corpus already uses, read the way it uses them.
    #[test]
    fn the_conventions_already_in_the_corpus_are_the_ones_read() {
        let src = "\
## ✅ B2 complete — geometry on screen
## 24. ⚠️ RETRACTED — `0x58` is a plain immediate
## 0z — ~~iPodLinux does not boot~~ · IT BOOTS, 2026-08-20
### ⚠️ The first render was right for the wrong reason
## 5. Transport — the channel table
";
        let h = headings(src);
        assert_eq!(h.len(), 5);
        assert_eq!(h[0].state, State::Settled);
        // RETRACTED wins over the warning sign: what the heading is FOR is the withdrawal.
        assert_eq!(h[1].state, State::Retracted);
        assert_eq!(h[2].state, State::Retracted);
        assert_eq!(h[2].date.as_deref(), Some("2026-08-20"));
        assert_eq!(h[3].state, State::Corrected);
        assert_eq!(h[4].state, State::Plain);
        assert!(!h[0].text.contains('✅'), "the marker is stripped from the text");
    }

    /// **A `#` inside a fenced block is not a heading.**
    ///
    /// The corpus's recipes are full of shell comments, and every one of them would otherwise become
    /// a finding. Measured before this guard existed: the count was wrong by hundreds.
    #[test]
    fn fenced_blocks_are_not_read_for_headings() {
        let src = "\
## A real heading
```sh
## not a heading, a shell comment
ipod-boot retail --clock=5
```
## Another real one
";
        let h = headings(src);
        assert_eq!(h.len(), 2, "a fenced comment was read as a heading");
        assert_eq!(h[1].text, "Another real one");
    }

    /// The newest dated heading is the document's current answer, wherever it sits.
    #[test]
    fn the_newest_dated_heading_is_what_stands() {
        let d = Doc {
            name: "x.md".into(),
            headings: headings(
                "\
## 22. The failure has a name (2026-08-14)
## 24. ⚠️ RETRACTED — the search was broken (2026-08-15)
## 25. The real answer (2026-08-19)
## 26. Undated prose that follows it
",
            ),
        };
        let n = d.newest().expect("something is dated");
        assert_eq!(n.date.as_deref(), Some("2026-08-19"));
        assert!(n.text.contains("real answer"));
        assert_eq!(d.count(State::Retracted), 1);
    }

    /// A pipe in a heading must not break the table it is rendered into.
    #[test]
    fn a_heading_cannot_break_the_table() {
        assert!(trim("a | b", 40).contains("\\|"));
        assert!(trim(&"x".repeat(200), 20).ends_with('…'));
    }

    /// **The index and the corpus agree — and if they do not, this rewrites it and fails.**
    ///
    /// The generator is not a command anybody has to remember. Drift arrives as a red test with the
    /// correct file already on disk.
    #[test]
    fn findings_md_matches_the_corpus() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../research")
            .canonicalize()
            .expect("research/");
        let docs = read_dir(&dir);
        assert!(!docs.is_empty(), "no research documents found");
        write_if_changed(&dir.join("FINDINGS.md"), &render(&docs));
    }
}
