//! Every iPod Apple made, keyed by the model number its own NOR reports.
//!
//! **Generated, not typed.** The rows are transcribed mechanically from libgpod's
//! `ipod_model_table` (`src/itdb_device.c`) — the table iTunes-compatible software has used for
//! twenty years. A table this size retyped by hand is where silent errors live, so it is not
//! retyped: regenerate by re-running the extraction over a fresh copy of that file.
//!
//! ## Why this and not iTunes
//!
//! iTunes has no model table. Checked directly against iTunes 12.8 — `iTunes.exe`,
//! `iPodUpdaterExt.dll` and `iPodService.exe` contain **no** model code in either ASCII or UTF-16.
//! iTunes works from the `FamilyID` a device reports plus a per-device log in `iPodDevices.xml`; it
//! never needed one. The colour/capacity mapping lives in Apple's published "Identify your iPod
//! model" pages, which is where libgpod's table came from.
//!
//! Corroborated where we can: macOS 27's `AMPDevices.framework` ships per-model artwork named
//! `iPod<FamilyID>-<Colour>`, and for family 6 (iPod with Video) it has exactly `iPod6-White`,
//! `iPod6-Black` and `iPod6-BlackRed` — the same three colours this table gives, from an
//! independent source. And our own `MA146` resolves to black, which is what our NOR draws.
//!
//! ## What it is *not*
//!
//! It is not a serial-number table. Nothing maps a serial's last three characters to a model here,
//! because no such mapping is available — see [`crate::identity::Identity::generate`].

/// A model constant, exactly as libgpod names it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum IpodModel {
    ClassicBlack,
    ClassicSilver,
    Color,
    ColorU2,
    Ipad,
    Iphone1,
    IphoneBlack,
    IphoneWhite,
    Mini,
    MiniBlue,
    MiniGold,
    MiniGreen,
    MiniPink,
    NanoBlack,
    NanoBlue,
    NanoGreen,
    NanoOrange,
    NanoPink,
    NanoPurple,
    NanoRed,
    NanoSilver,
    NanoWhite,
    NanoYellow,
    Regular,
    RegularU2,
    Shuffle,
    ShuffleBlack,
    ShuffleBlue,
    ShuffleGold,
    ShuffleGreen,
    ShuffleOrange,
    ShufflePink,
    ShufflePurple,
    ShuffleRed,
    ShuffleSilver,
    ShuffleStainless,
    TouchSilver,
    VideoBlack,
    VideoU2,
    VideoWhite,
}

/// A generation constant, exactly as libgpod names it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Generation {
    Classic1,
    Classic2,
    Classic3,
    First,
    Fourth,
    Ipad1,
    Iphone1,
    Iphone2,
    Iphone3,
    Iphone4,
    Mini1,
    Mini2,
    Nano1,
    Nano2,
    Nano3,
    Nano4,
    Nano5,
    Nano6,
    Photo,
    Second,
    Shuffle1,
    Shuffle2,
    Shuffle3,
    Shuffle4,
    Third,
    Touch1,
    Touch2,
    Touch3,
    Touch4,
    Video1,
    Video2,
}

impl IpodModel {
    /// The colour this constant names, if it names one. Many early models came in one colour and
    /// say nothing about it — those are `Unspecified` rather than being guessed at as white.
    pub fn colour(self) -> crate::identity::Colour {
        use crate::identity::Colour;
        match self {
            IpodModel::ClassicBlack => Colour::Black,
            IpodModel::ClassicSilver => Colour::Silver,
            IpodModel::Color => Colour::Unspecified,
            IpodModel::ColorU2 => Colour::U2,
            IpodModel::Ipad => Colour::Unspecified,
            IpodModel::Iphone1 => Colour::Unspecified,
            IpodModel::IphoneBlack => Colour::Black,
            IpodModel::IphoneWhite => Colour::White,
            IpodModel::Mini => Colour::Unspecified,
            IpodModel::MiniBlue => Colour::Blue,
            IpodModel::MiniGold => Colour::Gold,
            IpodModel::MiniGreen => Colour::Green,
            IpodModel::MiniPink => Colour::Pink,
            IpodModel::NanoBlack => Colour::Black,
            IpodModel::NanoBlue => Colour::Blue,
            IpodModel::NanoGreen => Colour::Green,
            IpodModel::NanoOrange => Colour::Orange,
            IpodModel::NanoPink => Colour::Pink,
            IpodModel::NanoPurple => Colour::Purple,
            IpodModel::NanoRed => Colour::Red,
            IpodModel::NanoSilver => Colour::Silver,
            IpodModel::NanoWhite => Colour::White,
            IpodModel::NanoYellow => Colour::Yellow,
            IpodModel::Regular => Colour::Unspecified,
            IpodModel::RegularU2 => Colour::U2,
            IpodModel::Shuffle => Colour::Unspecified,
            IpodModel::ShuffleBlack => Colour::Black,
            IpodModel::ShuffleBlue => Colour::Blue,
            IpodModel::ShuffleGold => Colour::Gold,
            IpodModel::ShuffleGreen => Colour::Green,
            IpodModel::ShuffleOrange => Colour::Orange,
            IpodModel::ShufflePink => Colour::Pink,
            IpodModel::ShufflePurple => Colour::Purple,
            IpodModel::ShuffleRed => Colour::Red,
            IpodModel::ShuffleSilver => Colour::Silver,
            IpodModel::ShuffleStainless => Colour::Stainless,
            IpodModel::TouchSilver => Colour::Silver,
            IpodModel::VideoBlack => Colour::Black,
            IpodModel::VideoU2 => Colour::U2,
            IpodModel::VideoWhite => Colour::White,
        }
    }
}

/// One row: what a `Mod#` means.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Row {
    /// The table key — four characters, e.g. `A146`.
    pub number: &'static str,
    pub capacity_gb: u16,
    pub model: IpodModel,
    pub generation: Generation,
}

/// Every row of libgpod's table — 197 of them.
pub const MODELS: &[Row] = &[
    Row { number: "8513", capacity_gb: 5, model: IpodModel::Regular, generation: Generation::First },
    Row { number: "8541", capacity_gb: 5, model: IpodModel::Regular, generation: Generation::First },
    Row { number: "8697", capacity_gb: 5, model: IpodModel::Regular, generation: Generation::First },
    Row { number: "8709", capacity_gb: 10, model: IpodModel::Regular, generation: Generation::First },
    Row { number: "8737", capacity_gb: 10, model: IpodModel::Regular, generation: Generation::Second },
    Row { number: "8740", capacity_gb: 10, model: IpodModel::Regular, generation: Generation::Second },
    Row { number: "8738", capacity_gb: 20, model: IpodModel::Regular, generation: Generation::Second },
    Row { number: "8741", capacity_gb: 20, model: IpodModel::Regular, generation: Generation::Second },
    Row { number: "8976", capacity_gb: 10, model: IpodModel::Regular, generation: Generation::Third },
    Row { number: "8946", capacity_gb: 15, model: IpodModel::Regular, generation: Generation::Third },
    Row { number: "9460", capacity_gb: 15, model: IpodModel::Regular, generation: Generation::Third },
    Row { number: "9244", capacity_gb: 20, model: IpodModel::Regular, generation: Generation::Third },
    Row { number: "8948", capacity_gb: 30, model: IpodModel::Regular, generation: Generation::Third },
    Row { number: "9245", capacity_gb: 40, model: IpodModel::Regular, generation: Generation::Third },
    Row { number: "9282", capacity_gb: 20, model: IpodModel::Regular, generation: Generation::Fourth },
    Row { number: "9787", capacity_gb: 25, model: IpodModel::RegularU2, generation: Generation::Fourth },
    Row { number: "9268", capacity_gb: 40, model: IpodModel::Regular, generation: Generation::Fourth },
    Row { number: "9160", capacity_gb: 4, model: IpodModel::Mini, generation: Generation::Mini1 },
    Row { number: "9436", capacity_gb: 4, model: IpodModel::MiniBlue, generation: Generation::Mini1 },
    Row { number: "9435", capacity_gb: 4, model: IpodModel::MiniPink, generation: Generation::Mini1 },
    Row { number: "9434", capacity_gb: 4, model: IpodModel::MiniGreen, generation: Generation::Mini1 },
    Row { number: "9437", capacity_gb: 4, model: IpodModel::MiniGold, generation: Generation::Mini1 },
    Row { number: "9800", capacity_gb: 4, model: IpodModel::Mini, generation: Generation::Mini2 },
    Row { number: "9802", capacity_gb: 4, model: IpodModel::MiniBlue, generation: Generation::Mini2 },
    Row { number: "9804", capacity_gb: 4, model: IpodModel::MiniPink, generation: Generation::Mini2 },
    Row { number: "9806", capacity_gb: 4, model: IpodModel::MiniGreen, generation: Generation::Mini2 },
    Row { number: "9801", capacity_gb: 6, model: IpodModel::Mini, generation: Generation::Mini2 },
    Row { number: "9803", capacity_gb: 6, model: IpodModel::MiniBlue, generation: Generation::Mini2 },
    Row { number: "9805", capacity_gb: 6, model: IpodModel::MiniPink, generation: Generation::Mini2 },
    Row { number: "9807", capacity_gb: 6, model: IpodModel::MiniGreen, generation: Generation::Mini2 },
    Row { number: "A079", capacity_gb: 20, model: IpodModel::Color, generation: Generation::Photo },
    Row { number: "A127", capacity_gb: 20, model: IpodModel::ColorU2, generation: Generation::Photo },
    Row { number: "9829", capacity_gb: 30, model: IpodModel::Color, generation: Generation::Photo },
    Row { number: "9585", capacity_gb: 40, model: IpodModel::Color, generation: Generation::Photo },
    Row { number: "9830", capacity_gb: 60, model: IpodModel::Color, generation: Generation::Photo },
    Row { number: "9586", capacity_gb: 60, model: IpodModel::Color, generation: Generation::Photo },
    Row { number: "9725", capacity_gb: 1, model: IpodModel::Shuffle, generation: Generation::Shuffle1 },
    Row { number: "A546", capacity_gb: 1, model: IpodModel::ShuffleSilver, generation: Generation::Shuffle2 },
    Row { number: "A947", capacity_gb: 1, model: IpodModel::ShufflePink, generation: Generation::Shuffle2 },
    Row { number: "A949", capacity_gb: 1, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle2 },
    Row { number: "A951", capacity_gb: 1, model: IpodModel::ShuffleGreen, generation: Generation::Shuffle2 },
    Row { number: "A953", capacity_gb: 1, model: IpodModel::ShuffleOrange, generation: Generation::Shuffle2 },
    Row { number: "C167", capacity_gb: 1, model: IpodModel::ShuffleGold, generation: Generation::Shuffle2 },
    Row { number: "B225", capacity_gb: 1, model: IpodModel::ShuffleSilver, generation: Generation::Shuffle2 },
    Row { number: "B233", capacity_gb: 1, model: IpodModel::ShufflePurple, generation: Generation::Shuffle2 },
    Row { number: "B231", capacity_gb: 1, model: IpodModel::ShuffleRed, generation: Generation::Shuffle2 },
    Row { number: "B227", capacity_gb: 1, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle2 },
    Row { number: "B228", capacity_gb: 1, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle2 },
    Row { number: "B229", capacity_gb: 1, model: IpodModel::ShuffleGreen, generation: Generation::Shuffle2 },
    Row { number: "B518", capacity_gb: 2, model: IpodModel::ShuffleSilver, generation: Generation::Shuffle2 },
    Row { number: "B520", capacity_gb: 2, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle2 },
    Row { number: "B522", capacity_gb: 2, model: IpodModel::ShuffleGreen, generation: Generation::Shuffle2 },
    Row { number: "B524", capacity_gb: 2, model: IpodModel::ShuffleRed, generation: Generation::Shuffle2 },
    Row { number: "B526", capacity_gb: 2, model: IpodModel::ShufflePurple, generation: Generation::Shuffle2 },
    Row { number: "C306", capacity_gb: 2, model: IpodModel::ShuffleSilver, generation: Generation::Shuffle3 },
    Row { number: "C323", capacity_gb: 2, model: IpodModel::ShuffleBlack, generation: Generation::Shuffle3 },
    Row { number: "C381", capacity_gb: 2, model: IpodModel::ShuffleGreen, generation: Generation::Shuffle3 },
    Row { number: "C384", capacity_gb: 2, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle3 },
    Row { number: "C387", capacity_gb: 2, model: IpodModel::ShufflePink, generation: Generation::Shuffle3 },
    Row { number: "B867", capacity_gb: 4, model: IpodModel::ShuffleSilver, generation: Generation::Shuffle3 },
    Row { number: "C164", capacity_gb: 4, model: IpodModel::ShuffleBlack, generation: Generation::Shuffle3 },
    Row { number: "C303", capacity_gb: 4, model: IpodModel::ShuffleStainless, generation: Generation::Shuffle3 },
    Row { number: "C307", capacity_gb: 4, model: IpodModel::ShuffleGreen, generation: Generation::Shuffle3 },
    Row { number: "C328", capacity_gb: 4, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle3 },
    Row { number: "C331", capacity_gb: 4, model: IpodModel::ShufflePink, generation: Generation::Shuffle3 },
    Row { number: "C584", capacity_gb: 2, model: IpodModel::ShuffleSilver, generation: Generation::Shuffle4 },
    Row { number: "C585", capacity_gb: 2, model: IpodModel::ShufflePink, generation: Generation::Shuffle4 },
    Row { number: "C749", capacity_gb: 2, model: IpodModel::ShuffleOrange, generation: Generation::Shuffle4 },
    Row { number: "C750", capacity_gb: 2, model: IpodModel::ShuffleGreen, generation: Generation::Shuffle4 },
    Row { number: "C751", capacity_gb: 2, model: IpodModel::ShuffleBlue, generation: Generation::Shuffle4 },
    Row { number: "A350", capacity_gb: 1, model: IpodModel::NanoWhite, generation: Generation::Nano1 },
    Row { number: "A352", capacity_gb: 1, model: IpodModel::NanoBlack, generation: Generation::Nano1 },
    Row { number: "A004", capacity_gb: 2, model: IpodModel::NanoWhite, generation: Generation::Nano1 },
    Row { number: "A099", capacity_gb: 2, model: IpodModel::NanoBlack, generation: Generation::Nano1 },
    Row { number: "A005", capacity_gb: 4, model: IpodModel::NanoWhite, generation: Generation::Nano1 },
    Row { number: "A107", capacity_gb: 4, model: IpodModel::NanoBlack, generation: Generation::Nano1 },
    Row { number: "A002", capacity_gb: 30, model: IpodModel::VideoWhite, generation: Generation::Video1 },
    Row { number: "A146", capacity_gb: 30, model: IpodModel::VideoBlack, generation: Generation::Video1 },
    Row { number: "A003", capacity_gb: 60, model: IpodModel::VideoWhite, generation: Generation::Video1 },
    Row { number: "A147", capacity_gb: 60, model: IpodModel::VideoBlack, generation: Generation::Video1 },
    Row { number: "A452", capacity_gb: 30, model: IpodModel::VideoU2, generation: Generation::Video1 },
    Row { number: "A444", capacity_gb: 30, model: IpodModel::VideoWhite, generation: Generation::Video2 },
    Row { number: "A446", capacity_gb: 30, model: IpodModel::VideoBlack, generation: Generation::Video2 },
    Row { number: "A664", capacity_gb: 30, model: IpodModel::VideoU2, generation: Generation::Video2 },
    Row { number: "A448", capacity_gb: 80, model: IpodModel::VideoWhite, generation: Generation::Video2 },
    Row { number: "A450", capacity_gb: 80, model: IpodModel::VideoBlack, generation: Generation::Video2 },
    Row { number: "A477", capacity_gb: 2, model: IpodModel::NanoSilver, generation: Generation::Nano2 },
    Row { number: "A426", capacity_gb: 4, model: IpodModel::NanoSilver, generation: Generation::Nano2 },
    Row { number: "A428", capacity_gb: 4, model: IpodModel::NanoBlue, generation: Generation::Nano2 },
    Row { number: "A487", capacity_gb: 4, model: IpodModel::NanoGreen, generation: Generation::Nano2 },
    Row { number: "A489", capacity_gb: 4, model: IpodModel::NanoPink, generation: Generation::Nano2 },
    Row { number: "A725", capacity_gb: 4, model: IpodModel::NanoRed, generation: Generation::Nano2 },
    Row { number: "A726", capacity_gb: 8, model: IpodModel::NanoRed, generation: Generation::Nano2 },
    Row { number: "A497", capacity_gb: 8, model: IpodModel::NanoBlack, generation: Generation::Nano2 },
    Row { number: "E436", capacity_gb: 40, model: IpodModel::Regular, generation: Generation::Fourth },
    Row { number: "S492", capacity_gb: 30, model: IpodModel::Color, generation: Generation::Photo },
    Row { number: "B029", capacity_gb: 80, model: IpodModel::ClassicSilver, generation: Generation::Classic1 },
    Row { number: "B147", capacity_gb: 80, model: IpodModel::ClassicBlack, generation: Generation::Classic1 },
    Row { number: "B145", capacity_gb: 160, model: IpodModel::ClassicSilver, generation: Generation::Classic1 },
    Row { number: "B150", capacity_gb: 160, model: IpodModel::ClassicBlack, generation: Generation::Classic1 },
    Row { number: "B562", capacity_gb: 120, model: IpodModel::ClassicSilver, generation: Generation::Classic2 },
    Row { number: "B565", capacity_gb: 120, model: IpodModel::ClassicBlack, generation: Generation::Classic2 },
    Row { number: "C293", capacity_gb: 160, model: IpodModel::ClassicSilver, generation: Generation::Classic3 },
    Row { number: "C297", capacity_gb: 160, model: IpodModel::ClassicBlack, generation: Generation::Classic3 },
    Row { number: "A978", capacity_gb: 4, model: IpodModel::NanoSilver, generation: Generation::Nano3 },
    Row { number: "A980", capacity_gb: 8, model: IpodModel::NanoSilver, generation: Generation::Nano3 },
    Row { number: "B261", capacity_gb: 8, model: IpodModel::NanoBlack, generation: Generation::Nano3 },
    Row { number: "B249", capacity_gb: 8, model: IpodModel::NanoBlue, generation: Generation::Nano3 },
    Row { number: "B253", capacity_gb: 8, model: IpodModel::NanoGreen, generation: Generation::Nano3 },
    Row { number: "B257", capacity_gb: 8, model: IpodModel::NanoRed, generation: Generation::Nano3 },
    Row { number: "B480", capacity_gb: 4, model: IpodModel::NanoSilver, generation: Generation::Nano4 },
    Row { number: "B651", capacity_gb: 4, model: IpodModel::NanoBlue, generation: Generation::Nano4 },
    Row { number: "B654", capacity_gb: 4, model: IpodModel::NanoPink, generation: Generation::Nano4 },
    Row { number: "B657", capacity_gb: 4, model: IpodModel::NanoPurple, generation: Generation::Nano4 },
    Row { number: "B660", capacity_gb: 4, model: IpodModel::NanoOrange, generation: Generation::Nano4 },
    Row { number: "B663", capacity_gb: 4, model: IpodModel::NanoGreen, generation: Generation::Nano4 },
    Row { number: "B666", capacity_gb: 4, model: IpodModel::NanoYellow, generation: Generation::Nano4 },
    Row { number: "B598", capacity_gb: 8, model: IpodModel::NanoSilver, generation: Generation::Nano4 },
    Row { number: "B732", capacity_gb: 8, model: IpodModel::NanoBlue, generation: Generation::Nano4 },
    Row { number: "B735", capacity_gb: 8, model: IpodModel::NanoPink, generation: Generation::Nano4 },
    Row { number: "B739", capacity_gb: 8, model: IpodModel::NanoPurple, generation: Generation::Nano4 },
    Row { number: "B742", capacity_gb: 8, model: IpodModel::NanoOrange, generation: Generation::Nano4 },
    Row { number: "B745", capacity_gb: 8, model: IpodModel::NanoGreen, generation: Generation::Nano4 },
    Row { number: "B748", capacity_gb: 8, model: IpodModel::NanoYellow, generation: Generation::Nano4 },
    Row { number: "B751", capacity_gb: 8, model: IpodModel::NanoRed, generation: Generation::Nano4 },
    Row { number: "B754", capacity_gb: 8, model: IpodModel::NanoBlack, generation: Generation::Nano4 },
    Row { number: "B903", capacity_gb: 16, model: IpodModel::NanoSilver, generation: Generation::Nano4 },
    Row { number: "B905", capacity_gb: 16, model: IpodModel::NanoBlue, generation: Generation::Nano4 },
    Row { number: "B907", capacity_gb: 16, model: IpodModel::NanoPink, generation: Generation::Nano4 },
    Row { number: "B909", capacity_gb: 16, model: IpodModel::NanoPurple, generation: Generation::Nano4 },
    Row { number: "B911", capacity_gb: 16, model: IpodModel::NanoOrange, generation: Generation::Nano4 },
    Row { number: "B913", capacity_gb: 16, model: IpodModel::NanoGreen, generation: Generation::Nano4 },
    Row { number: "B915", capacity_gb: 16, model: IpodModel::NanoYellow, generation: Generation::Nano4 },
    Row { number: "B917", capacity_gb: 16, model: IpodModel::NanoRed, generation: Generation::Nano4 },
    Row { number: "B918", capacity_gb: 16, model: IpodModel::NanoBlack, generation: Generation::Nano4 },
    Row { number: "C027", capacity_gb: 8, model: IpodModel::NanoSilver, generation: Generation::Nano5 },
    Row { number: "C031", capacity_gb: 8, model: IpodModel::NanoBlack, generation: Generation::Nano5 },
    Row { number: "C034", capacity_gb: 8, model: IpodModel::NanoPurple, generation: Generation::Nano5 },
    Row { number: "C037", capacity_gb: 8, model: IpodModel::NanoBlue, generation: Generation::Nano5 },
    Row { number: "C040", capacity_gb: 8, model: IpodModel::NanoGreen, generation: Generation::Nano5 },
    Row { number: "C043", capacity_gb: 8, model: IpodModel::NanoYellow, generation: Generation::Nano5 },
    Row { number: "C046", capacity_gb: 8, model: IpodModel::NanoOrange, generation: Generation::Nano5 },
    Row { number: "C049", capacity_gb: 8, model: IpodModel::NanoRed, generation: Generation::Nano5 },
    Row { number: "C050", capacity_gb: 8, model: IpodModel::NanoPink, generation: Generation::Nano5 },
    Row { number: "C060", capacity_gb: 16, model: IpodModel::NanoSilver, generation: Generation::Nano5 },
    Row { number: "C062", capacity_gb: 16, model: IpodModel::NanoBlack, generation: Generation::Nano5 },
    Row { number: "C064", capacity_gb: 16, model: IpodModel::NanoPurple, generation: Generation::Nano5 },
    Row { number: "C066", capacity_gb: 16, model: IpodModel::NanoBlue, generation: Generation::Nano5 },
    Row { number: "C068", capacity_gb: 16, model: IpodModel::NanoGreen, generation: Generation::Nano5 },
    Row { number: "C070", capacity_gb: 16, model: IpodModel::NanoYellow, generation: Generation::Nano5 },
    Row { number: "C072", capacity_gb: 16, model: IpodModel::NanoOrange, generation: Generation::Nano5 },
    Row { number: "C074", capacity_gb: 16, model: IpodModel::NanoRed, generation: Generation::Nano5 },
    Row { number: "C075", capacity_gb: 16, model: IpodModel::NanoPink, generation: Generation::Nano5 },
    Row { number: "C525", capacity_gb: 8, model: IpodModel::NanoSilver, generation: Generation::Nano6 },
    Row { number: "C688", capacity_gb: 8, model: IpodModel::NanoBlack, generation: Generation::Nano6 },
    Row { number: "C689", capacity_gb: 8, model: IpodModel::NanoBlue, generation: Generation::Nano6 },
    Row { number: "C690", capacity_gb: 8, model: IpodModel::NanoGreen, generation: Generation::Nano6 },
    Row { number: "C691", capacity_gb: 8, model: IpodModel::NanoOrange, generation: Generation::Nano6 },
    Row { number: "C692", capacity_gb: 8, model: IpodModel::NanoPink, generation: Generation::Nano6 },
    Row { number: "C693", capacity_gb: 8, model: IpodModel::NanoRed, generation: Generation::Nano6 },
    Row { number: "C526", capacity_gb: 16, model: IpodModel::NanoSilver, generation: Generation::Nano6 },
    Row { number: "C694", capacity_gb: 16, model: IpodModel::NanoBlack, generation: Generation::Nano6 },
    Row { number: "C695", capacity_gb: 16, model: IpodModel::NanoBlue, generation: Generation::Nano6 },
    Row { number: "C696", capacity_gb: 16, model: IpodModel::NanoGreen, generation: Generation::Nano6 },
    Row { number: "C697", capacity_gb: 16, model: IpodModel::NanoOrange, generation: Generation::Nano6 },
    Row { number: "C698", capacity_gb: 16, model: IpodModel::NanoPink, generation: Generation::Nano6 },
    Row { number: "C699", capacity_gb: 16, model: IpodModel::NanoRed, generation: Generation::Nano6 },
    Row { number: "A623", capacity_gb: 8, model: IpodModel::TouchSilver, generation: Generation::Touch1 },
    Row { number: "A627", capacity_gb: 16, model: IpodModel::TouchSilver, generation: Generation::Touch1 },
    Row { number: "B376", capacity_gb: 32, model: IpodModel::TouchSilver, generation: Generation::Touch1 },
    Row { number: "B528", capacity_gb: 8, model: IpodModel::TouchSilver, generation: Generation::Touch2 },
    Row { number: "B531", capacity_gb: 16, model: IpodModel::TouchSilver, generation: Generation::Touch2 },
    Row { number: "B533", capacity_gb: 32, model: IpodModel::TouchSilver, generation: Generation::Touch2 },
    Row { number: "C086", capacity_gb: 8, model: IpodModel::TouchSilver, generation: Generation::Touch2 },
    Row { number: "C008", capacity_gb: 32, model: IpodModel::TouchSilver, generation: Generation::Touch3 },
    Row { number: "C011", capacity_gb: 64, model: IpodModel::TouchSilver, generation: Generation::Touch3 },
    Row { number: "C540", capacity_gb: 8, model: IpodModel::TouchSilver, generation: Generation::Touch4 },
    Row { number: "C544", capacity_gb: 32, model: IpodModel::TouchSilver, generation: Generation::Touch4 },
    Row { number: "C547", capacity_gb: 64, model: IpodModel::TouchSilver, generation: Generation::Touch4 },
    Row { number: "A501", capacity_gb: 4, model: IpodModel::Iphone1, generation: Generation::Iphone1 },
    Row { number: "A712", capacity_gb: 8, model: IpodModel::Iphone1, generation: Generation::Iphone1 },
    Row { number: "B384", capacity_gb: 16, model: IpodModel::Iphone1, generation: Generation::Iphone1 },
    Row { number: "B046", capacity_gb: 8, model: IpodModel::IphoneBlack, generation: Generation::Iphone2 },
    Row { number: "B500", capacity_gb: 16, model: IpodModel::IphoneWhite, generation: Generation::Iphone2 },
    Row { number: "B048", capacity_gb: 16, model: IpodModel::IphoneBlack, generation: Generation::Iphone2 },
    Row { number: "B496", capacity_gb: 16, model: IpodModel::IphoneBlack, generation: Generation::Iphone2 },
    Row { number: "C131", capacity_gb: 16, model: IpodModel::IphoneBlack, generation: Generation::Iphone3 },
    Row { number: "C133", capacity_gb: 32, model: IpodModel::IphoneBlack, generation: Generation::Iphone3 },
    Row { number: "C134", capacity_gb: 32, model: IpodModel::IphoneWhite, generation: Generation::Iphone3 },
    Row { number: "C603", capacity_gb: 16, model: IpodModel::IphoneBlack, generation: Generation::Iphone4 },
    Row { number: "C605", capacity_gb: 32, model: IpodModel::IphoneBlack, generation: Generation::Iphone4 },
    Row { number: "B292", capacity_gb: 16, model: IpodModel::Ipad, generation: Generation::Ipad1 },
    Row { number: "B293", capacity_gb: 32, model: IpodModel::Ipad, generation: Generation::Ipad1 },
    Row { number: "B294", capacity_gb: 64, model: IpodModel::Ipad, generation: Generation::Ipad1 },
    Row { number: "C349", capacity_gb: 16, model: IpodModel::Ipad, generation: Generation::Ipad1 },
    Row { number: "C496", capacity_gb: 32, model: IpodModel::Ipad, generation: Generation::Ipad1 },
    Row { number: "C497", capacity_gb: 64, model: IpodModel::Ipad, generation: Generation::Ipad1 },
];
