//! Every number the drawn iPod, the window's own size constants and §9.6's vertical column are
//! made of — declared exactly once.
//!
//! `docs/GUI.md` §16.9 is the rule this file exists to keep: *the constants live in one place, the
//! tests read them, and a claim without a check is deleted rather than left standing.* The markup
//! gets these values through a `.slint` file generated by `build.rs`; the tests read this module
//! directly. So the test reads what the markup reads, and the hand-copied block that used to sit in
//! `main.rs`'s test module — with a comment admitting it was a known hole, and with a **stale copy
//! of a corrected ratio** in it — is gone.
//!
//! ── Two constraints on this file, both load-bearing ──────────────────────────────────────────
//!
//! **No `use` of anything outside `core` / `std`, and no inner attributes.** `build.rs` compiles
//! this same file (`#[path = "src/geometry.rs"] mod geometry;`), and a build script can see only
//! its own build-dependencies. A `use slint::…` here stops the build script compiling, and the
//! error points at `build.rs` rather than at the line that caused it.
//!
//! **Nothing here is persisted.** `k`, the measured client height and the too-short boolean are
//! recomputed every launch. A remembered `k` would survive a move from a 2× display to a 1× one and
//! put §9.6's shelf — the row carrying `write_target()` — below the bottom edge, which is the exact
//! failure §16.1 describes. No key for any of this appears in `settings.txt`, ever.

/// How a constant is rendered into Slint.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Unit {
    /// A fraction of `body-height`. Emitted as `out property <float>`.
    Ratio,
    /// A logical pixel length. Emitted as `out property <length>` with a `px` suffix.
    Px,
}

/// Defines each constant once, and **simultaneously builds the emit table**, so there is no second
/// list of "which constants exist" to fall out of step with the first.
macro_rules! geometry {
    ($( $(#[$doc:meta])* $name:ident : $unit:ident = $value:expr ; )*) => {
        $( $(#[$doc])* pub const $name: f64 = $value; )*

        /// Every constant, in declaration order: the Rust name, how to render it, and its value.
        ///
        /// Built by the same macro invocation that declares them, so a constant cannot be defined
        /// and then silently not emitted.
        pub const ALL: &[(&str, Unit, f64)] =
            &[ $( (stringify!($name), Unit::$unit, $name) ),* ];
    };
}

geometry! {
    // ── §6.6 the drawn device: every ratio is a fraction of body height ──
    //
    // Measured from Rockbox's own scale drawing of this device, except the screen's *size*, which
    // §6.6 took off the drawing: the drawing governs where the screen sits, the hardware governs
    // how big it is. `SCREEN_W` / `SCREEN_H` is exactly 4:3 by construction, which is the one rule
    // this project will not bend.

    /// Body width as a fraction of body height. 104.1 mm × 61.6 mm.
    BODY_ASPECT:      Ratio = 0.5917;
    /// 50.8 mm / 104.1 mm — the hardware's own width, not the drawing's.
    SCREEN_W:         Ratio = 0.48799;
    /// 38.1 mm / 104.1 mm. `SCREEN_W / SCREEN_H` is 4:3 to within 1e-5.
    SCREEN_H:         Ratio = 0.36599;
    /// Where the drawing puts the top of the active area. Equals [`left_inset`] to 0.00065.
    SCREEN_TOP:       Ratio = 0.0525;
    /// The black glass overhang, and it is the same on **all four** sides:
    /// `0.51999 − 0.48799 = 0.032` and `0.39799 − 0.36599 = 0.032`, so `0.016` per side.
    BEZEL_RATIO:      Ratio = 0.016;
    GLASS_CORNER_R:   Ratio = 0.008;
    CORNER_R:         Ratio = 0.0501;
    WHEEL_D:          Ratio = 0.3675;
    WHEEL_TOP:        Ratio = 0.5215;
    CENTRE_D:         Ratio = 0.1228;
    MARK_INSET:       Ratio = 0.024;
    MARK_W:           Ratio = 0.036;
    MARK_H:           Ratio = 0.024;
    PLAY_W:           Ratio = 0.040;
    MENU_TOP:         Ratio = 0.024;
    MENU_SIZE:        Ratio = 0.026;
    MENU_TRACK:       Ratio = 0.003;
    HOLD_W:           Ratio = 0.100;
    HOLD_H:           Ratio = 0.024;
    HOLD_INSET:       Ratio = 0.055;
    /// The carousel's neighbours, relative to the selected device.
    NEIGHBOUR_SCALE:  Ratio = 0.55;

    // ── §6.6 the physical hero ──

    /// **The body height at which one framebuffer pixel is one device pixel**, in PHYSICAL px.
    ///
    /// `320 / SCREEN_W` = 655.7511424414434, and `240 / SCREEN_H` = 655.7556 — the same number to
    /// four figures, which is the tell that the well is 4:3. Written as the quotient rather than as
    /// a typed 655.751 so that a re-measured `SCREEN_W` moves it.
    HERO_PHYS_1X:     Px = 320.0 / SCREEN_W;

    // ── §9.6 the vertical budget, logical px ──

    /// The only elastic term in the column; it absorbs all slack.
    MARGIN_TOP:       Px = 24.0;
    MARGIN_TOP_MIN:   Px = 0.0;
    /// The cradle outline is offset **outward** by this much.
    CRADLE_OVERHANG:  Px = 10.0;
    /// The focused state adds 2 px more, 4 px outside the overhang.
    FOCUS_GAP:        Px = 6.0;
    /// Overhang + focus ring, one side. Appears **twice** in the column — above the body as well as
    /// below it, which is the term the previous revision listed once and lost off the top edge.
    CRADLE_BAND:      Px = CRADLE_OVERHANG + FOCUS_GAP;
    GAP_1:            Px = 6.0;
    GAP_1_MIN:        Px = 2.0;
    CRADLE_LABEL:     Px = 24.0;
    GAP_2:            Px = 16.0;
    GAP_2_MIN:        Px = 8.0;
    /// Flush to the bottom edge, three rows.
    SHELF:            Px = 88.0;
    /// Everything in the column that is not the body, at minimum. Declared, then derived from the
    /// terms by `the_column_terms_sum_to_the_declared_chrome`.
    CHROME_MIN:       Px = 154.0;
    /// Everything in the column that is not the body, preferred.
    CHROME_PREF:      Px = 190.0;

    // ── §9.6 the horizontal budget, logical px ──

    DRAWER_W:         Px = 420.0;
    /// 20 each side of the well.
    WELL_AIR:         Px = 20.0;

    // ── The window's own four constants ──
    //
    // §16.1: these are plain constants and they must never read `hero`. If either height were bound
    // to the body the loop would close and oscillate, and this is the sentence that stops somebody
    // tidying it. `the_window_constants_do_not_read_the_hero` is the mechanical form of it.

    /// Derived in one line rather than in two disagreeing ones — see
    /// `the_min_width_derivation_sums_to_the_declared_minimum`.
    MIN_WIDTH:        Px = 880.0;
    /// **A floor, not a fit.** A minimum tall enough to guarantee the 1:1 panel would have to vary
    /// with `k` and `sf`, and a window minimum is a constant. This is the height below which even
    /// §9.5's replacement pane cannot be laid out; everything above it is the too-short boolean's
    /// job.
    ///
    /// **And the pane it defers to is not built**, which is worth saying here because this is the
    /// constant that makes the state reachable. `too-short` is computed, pushed in, and read by no
    /// markup (`window.slint:189`, declared and unused) — so between this floor and roughly 810
    /// logical the 655.751 px device and the caption row carrying `write_target()` are laid out
    /// past the bottom edge and drawn there. The previous `860px` did not fix that: it only made
    /// the state harder to reach by dragging, and it was a minimum no 1280 × 800 display can
    /// satisfy, so it guarded nothing on the display class §9.5 is actually about. **Retirement
    /// condition**, in the shape `research/04` uses: when §9.5's replacement pane reads
    /// `too-short`, delete this paragraph. `docs/GUI.md` §20 item 15 is the entry for it.
    MIN_HEIGHT:       Px = 400.0;
    PREF_WIDTH:       Px = 1180.0;
    /// The k = 1, sf = 1 case of body + [`CHROME_PREF`], rounded up. Not a round number.
    PREF_HEIGHT:      Px = 846.0;

    // ── The two small drawings (§6.6) ──
    //
    // The same drawing at a different `body-height`, and neither is a framebuffer, so neither has
    // a `k`.

    /// The drawer's Devices list.
    ROW_BODY:         Px = 40.0;
    /// A Parts row for an iPod resource.
    THUMB_BODY:       Px = 24.0;
}

// ── Rust-only. NOT emitted: not scalars Slint can hold, or not read by markup. ──

/// §16.10's sweep of display scale factors.
///
/// `#[cfg(test)]` rather than `#[allow(dead_code)]`: nothing outside a test sweeps scale factors,
/// and a constant kept alive by an allow is the shape §16.9 deletes.
#[cfg(test)]
pub const SF_SWEEP: [f64; 10] = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0, 3.5];

/// The largest whole-number framebuffer scale this program will choose.
///
/// A 4K portrait display could legitimately ask for 5 or 6; the clamp is the sweep's own bound and
/// it is stated here rather than hidden in an arithmetic accident.
pub const K_MAX: i32 = 8;

/// §9.6: drop below the threshold, restore 20 px above it.
///
/// The asymmetry is the whole point — a symmetric comparison flutters under a drag exactly at the
/// boundary, which is a window that flickers between two layouts while the mouse is down.
pub const HYSTERESIS: f64 = 20.0;

/// `SCREEN_W` → `"screen-w"`. The only mangling, and it is total.
pub fn slint_name(rust_name: &str) -> String {
    rust_name.to_ascii_lowercase().replace('_', "-")
}

/// Render one `f64` as a Slint numeric literal.
///
/// `{:?}` is the shortest round-tripping form, which is what we want — but for a value below about
/// 1e-4 it emits `1e-5`, and **Slint's lexer reads the `e` as a unit**. Every constant above formats
/// plainly; the assert is here so that a future one that does not fails the build script, with its
/// own value in the message, rather than failing the markup.
///
/// Verified rather than assumed: with this assert removed and a `TINY: Ratio = 1.0e-5` added, the
/// build stops at
///
/// ```text
/// error: Invalid unit 'e'. Valid units are: %, phx, px, cm, mm, in, pt, rem, s, ms, deg, grad,
///        turn, rad
///   --> …/out/geometry.slint:23:32
///    |
/// 23 |     out property <float> tiny: 1e-5;
/// ```
///
/// — pointing at a generated file nobody edited, which is the diagnosis this assert replaces.
//
// Compiled by `build.rs` as well as by the crate, and only the build script calls it — hence the
// allow. It comes off if the window ever needs to print a Slint literal at run time, which it does
// not today.
#[allow(dead_code)]
pub fn slint_number(v: f64) -> String {
    let s = format!("{v:?}");
    assert!(
        s.bytes().all(|b| b.is_ascii_digit() || b == b'.' || b == b'-'),
        "{s} is not a plain decimal; Slint's lexer reads the exponent as a unit"
    );
    s
}

/// The whole generated `.slint` file, as text.
///
/// Called by `build.rs` **and** by `the_generated_file_is_byte_identical_to_the_source_of_truth`,
/// so a non-deterministic byte here — a timestamp, a hash-map order, an absolute path — is caught
/// by a test rather than by four consecutive rebuilds that each recompile.
#[allow(dead_code)]
pub fn slint_source() -> String {
    let mut out = String::new();
    out.push_str("// generated by build.rs from src/geometry.rs — do not edit\n");
    out.push_str("export global Geometry {\n");
    for (name, unit, value) in ALL {
        let (ty, suffix) = match unit {
            Unit::Ratio => ("float", ""),
            Unit::Px => ("length", "px"),
        };
        out.push_str(&format!(
            "    out property <{ty}> {}: {}{suffix};\n",
            slint_name(name),
            slint_number(*value)
        ));
    }
    out.push_str("}\n");
    out
}

// ── The one-way arrow of §6.6 ───────────────────────────────────────────────────────────────────
//
// Nothing below takes a window. `hero` is pushed into the markup from Rust and never read back out
// of it, and the only way to keep that true is for the arithmetic to have no way of asking.

/// The symmetric inset of the screen from the left edge of the body.
///
/// An **output** since §6.6 took the screen's size off the drawing: `(BODY_ASPECT − SCREEN_W) / 2`.
/// It differs from [`SCREEN_TOP`] by 0.00065 of body height — 0.43 px at hero, 0.07 mm on a real
/// device — and that agreement is how the parse was confirmed to have found the display rather than
/// some other rectangle in a drawing full of rectangles.
pub fn left_inset() -> f64 {
    (BODY_ASPECT - SCREEN_W) / 2.0
}

/// The black surround, in physical pixels. 10.49, four sides, every `k`, every scale factor.
pub fn bezel_phys() -> f64 {
    BEZEL_RATIO * HERO_PHYS_1X
}

/// The body height in PHYSICAL pixels at framebuffer scale `k`.
pub fn hero_phys(k: i32) -> f64 {
    f64::from(k) * HERO_PHYS_1X
}

/// The body height in LOGICAL pixels — the length pushed into the markup.
pub fn hero_logical(k: i32, sf: f64) -> f64 {
    hero_phys(k) / sf
}

/// The whole-number framebuffer scale a given amount of logical height can hold.
///
/// Never below 1: a client shorter than [`CHROME_MIN`] floors negative and comes back as `k = 1`
/// with the too-short boolean set, which is §9.5 and is correct rather than a special case.
pub fn decide_k(avail_logical: f64, sf: f64) -> i32 {
    let raw = ((avail_logical - CHROME_MIN) * sf) / HERO_PHYS_1X;
    let k = raw.floor().max(1.0);
    (k as i32).min(K_MAX)
}

/// Walk a logical length up until it survives the round-trip through `f32` and back into physical
/// pixels — that is, until `f32(w) × sf` is **not below** the framebuffer it has to hold.
///
/// `Coord = f32` in `i-slint-core`, so the round-trip that matters is the f32 one, and **the walk
/// has to be in f32 steps**. The first version of this stepped `f64::next_up`, which is a relative
/// 2⁻⁵² — about 2⁻²⁹ of one step of the f32 grid it was trying to cross. Sixty-four of them cannot
/// move the f32 value at all, so the loop always ran out and handed back exactly what it was given.
/// It looked like it worked because in 120 of the 160 swept `sf × k` cases the plain division is
/// already exact; in the other 40 — every `sf` of 1.5, 1.75, 2.25, 3.0, 3.5 and some of 2.75 — the
/// panel came back a fraction of a pixel **short** of `k × 320`, which is a framebuffer column
/// thrown away wherever the renderer truncates rather than rounds. Measured, not assumed: the
/// sweep in `the_panel_is_an_exact_integer_number_of_device_pixels` reports 40 short before the
/// step is fixed and 0 after, and the worst overshoot afterwards is 0.00015 px — inside the black
/// glass, where nobody can see it.
pub fn next_up_until(target_phys: f64, sf: f64) -> f64 {
    let mut w = (target_phys / sf) as f32;
    for _ in 0..64 {
        if f64::from(w) * sf >= target_phys {
            return f64::from(w);
        }
        w = w.next_up();
    }
    f64::from(w)
}

/// The panel, in logical pixels, at framebuffer scale `k`.
pub fn panel_logical(k: i32, sf: f64) -> (f64, f64) {
    let k = f64::from(k);
    (
        next_up_until(k * 320.0, sf),
        next_up_until(k * 240.0, sf),
    )
}

/// The black glass, in physical pixels — **computed from the panel**, never from a ratio.
///
/// The previous revision computed `k` from a glass whose own ratio was 1.3066, so the two ratios
/// §6.6 exists to correct governed nothing except where the glass sat. Making the glass an output
/// is what stops a re-measured bezel silently flipping which axis bounds `k`.
pub fn glass_phys(k: i32) -> (f64, f64) {
    let k = f64::from(k);
    let b = 2.0 * bezel_phys();
    (k * 320.0 + b, k * 240.0 + b)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The text `build.rs` wrote into `OUT_DIR`, as the crate's own compile saw it.
    const GENERATED: &str = include_str!(concat!(env!("OUT_DIR"), "/geometry.slint"));

    const IPOD_SLINT: &str =
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/ui/ipod.slint"));
    const WINDOW_SLINT: &str =
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/ui/window.slint"));

    /// §9.6's `min-width` has ONE derivation, and this is it.
    ///
    /// The document's own parenthetical — *"12 handle + 24 + 389.3 + 24"* — summed to 449.3 beside a
    /// declared 880, which is two sources of truth for a load-bearing constant in the section whose
    /// rule is that constants live in one place. So the derivation becomes the check.
    #[test]
    fn the_min_width_derivation_sums_to_the_declared_minimum() {
        let needed = DRAWER_W
            + BODY_ASPECT * HERO_PHYS_1X
            + 2.0 * CRADLE_OVERHANG
            + 2.0 * FOCUS_GAP
            + 2.0 * WELL_AIR;
        assert!(
            (needed - MIN_WIDTH).abs() < 0.05,
            "the well needs {needed:.1} px and the window declares {MIN_WIDTH:.1}"
        );
    }

    /// §9.6: `min-height` is a **floor**, not a fit.
    ///
    /// A window whose declared minimum claimed to hold the device would be in silent conflict with
    /// the fidelity rule, and the layout wins that argument — which is what the test this replaces
    /// (`the_window_minimum_holds_the_device`) asserted as a *requirement*.
    //
    // The relationship between two declared constants IS the thing under test, so clippy's
    // "this assertion has a constant value" is describing the point rather than a defect. Not moved
    // into a `const` block on purpose: a failure here should name both numbers at test time, the
    // way every other check in this module does, rather than stop the build with a const-eval
    // panic.
    #[allow(clippy::assertions_on_constants)]
    #[test]
    fn the_minimum_height_is_a_floor_not_a_fit() {
        assert!(
            MIN_HEIGHT < HERO_PHYS_1X + CHROME_MIN,
            "a declared minimum of {MIN_HEIGHT:.0} that held a {:.0} px device would make the \
             too-short state unreachable, and §9.5 is a designed state",
            HERO_PHYS_1X + CHROME_MIN
        );
    }

    /// **The other half of that floor, and it does not exist yet — so the gap is asserted instead
    /// of left to be discovered.**
    ///
    /// `min-height` is 400 because §9.6 says a window minimum is a floor, and the state below the
    /// threshold is supposed to be replaced by §9.5's pane rather than laid out badly. `too-short`
    /// is computed with hysteresis and pushed in on every change — and **read by no markup**, so
    /// between 400 and ~810 logical the device and the caption row carrying `write_target()` are
    /// positioned past the bottom edge and drawn there.
    ///
    /// This is the self-retiring form the exemption list uses: it asserts that `too-short` still
    /// appears exactly once in `window.slint`, as its own declaration. The moment §9.5's pane reads
    /// it, this goes red — and whoever wrote the pane deletes this test, [`MIN_HEIGHT`]'s
    /// paragraph and `docs/GUI.md` §20 item 15 together. A gap nothing can fail on is a gap that
    /// gets forgotten.
    #[test]
    fn the_too_short_state_is_an_input_with_nothing_reading_it() {
        let uses: Vec<&str> = WINDOW_SLINT
            .lines()
            .map(str::trim)
            .filter(|l| l.contains("too-short"))
            .collect();
        assert_eq!(
            uses,
            vec!["in property <bool> too-short: false;"],
            "§9.5's pane reads `too-short` now — delete this test, MIN_HEIGHT's paragraph about it, \
             and GUI.md §20 item 15"
        );
        assert!(
            !IPOD_SLINT.contains("too-short"),
            "the drawing reads the window's too-short state; the same retirement applies"
        );
    }

    /// [`CHROME_MIN`] and [`CHROME_PREF`] are not typed-in totals.
    ///
    /// This is §16.10's `the_column_fits_the_declared_minimum`, re-expressed. Its stated assertion
    /// — `sum <= min_height` — is arithmetically impossible under §9.6's own numbers (809.751 ≤ 400
    /// holds at no `k` and no `sf`), so implementing it verbatim would produce a test that can only
    /// fail and would then be weakened until it passed. What §9.6 actually establishes is that the
    /// column's terms sum to the declared chrome, **including the cradle band above the body as
    /// well as below it**, and that is asserted here exactly.
    #[test]
    fn the_column_terms_sum_to_the_declared_chrome() {
        let min = MARGIN_TOP_MIN
            + CRADLE_BAND
            + CRADLE_BAND
            + GAP_1_MIN
            + CRADLE_LABEL
            + GAP_2_MIN
            + SHELF;
        assert_eq!(
            min, CHROME_MIN,
            "the minimum column sums to {min} and CHROME_MIN declares {CHROME_MIN}"
        );

        let pref =
            MARGIN_TOP + CRADLE_BAND + CRADLE_BAND + GAP_1 + CRADLE_LABEL + GAP_2 + SHELF;
        assert_eq!(
            pref, CHROME_PREF,
            "the preferred column sums to {pref} and CHROME_PREF declares {CHROME_PREF}"
        );
    }

    /// `preferred-height` is the k = 1, sf = 1 case of body + chrome, not a round number.
    #[test]
    fn the_preferred_height_holds_the_device_at_k_one() {
        let want = (HERO_PHYS_1X + CHROME_PREF).ceil();
        assert_eq!(
            want, PREF_HEIGHT,
            "the body plus the preferred column is {want} and PREF_HEIGHT declares {PREF_HEIGHT}"
        );
    }

    /// §6.6's tell that the well is 4:3: the two derivations of the hero agree.
    #[test]
    fn the_two_hero_derivations_agree() {
        let from_h = 240.0 / SCREEN_H;
        assert!(
            (HERO_PHYS_1X - from_h).abs() < 0.01,
            "320/SCREEN_W is {HERO_PHYS_1X:.4} and 240/SCREEN_H is {from_h:.4}; they are supposed \
             to be the same number to four figures"
        );
        let ratio = SCREEN_W / SCREEN_H;
        assert!(
            (ratio - 4.0 / 3.0).abs() < 1e-5,
            "the well is {ratio:.5}, not 4:3 — a 320×240 buffer would be stretched in one axis only"
        );
    }

    /// §16.10 and §20 item 10. **The panel is a whole number of device pixels at every scale
    /// factor and every `k`, and never one short of it.**
    ///
    /// The framebuffer is 320 × 240 and §2.8 allows whole-number scales only, so the drawn panel
    /// has to land on exactly `k × 320` by `k × 240` **physical** pixels. Two halves, and the
    /// second is the one that was broken:
    ///
    /// - it must **round** to that, or a row or column of the frame is duplicated or dropped;
    /// - it must not be **below** it, because a renderer that truncates rather than rounds turns
    ///   `319.99999` into 319 — the 560 px bug at a hundredth of the scale.
    ///
    /// It swept `sf ∈ SF_SWEEP × k ∈ 1..=K_MAX` — 160 cases — and found 40 short, which is what
    /// made [`next_up_until`] a real function rather than a decorative one: it was stepping f64
    /// ULPs across an f32 grid and could never move the value it was handed. The existing
    /// `the_panel_is_an_exact_whole_number_of_pixels` in `main.rs` checks `k = 1, sf = 1`, which
    /// §16.10 says is precisely the case that is not interesting.
    #[test]
    fn the_panel_is_an_exact_integer_number_of_device_pixels() {
        let mut short = Vec::new();
        for sf in SF_SWEEP {
            for k in 1..=K_MAX {
                let (w, h) = panel_logical(k, sf);
                // Through `f32` and back, because that is what the markup holds and what the
                // renderer multiplies: `Coord = f32` in `i-slint-core`.
                for (logical, base, axis) in [(w, 320.0, "across"), (h, 240.0, "down")] {
                    let want = f64::from(k) * base;
                    let phys = f64::from(logical as f32) * sf;
                    if phys < want {
                        short.push(format!(
                            "sf {sf} k {k} {axis}: {phys:.6} physical for a {want} px \
                             framebuffer, {:.6} short",
                            want - phys
                        ));
                    }
                    assert_eq!(
                        phys.round() as i64,
                        want as i64,
                        "sf {sf} k {k} {axis}: {logical:.6} logical draws {phys:.6} physical, \
                         and the framebuffer is {want}"
                    );
                }
                // The same multiple on both axes, or it is a stretch rather than a scale — which
                // is what the pre-§6.6 `0.4866 / 0.3672` pair actually did.
                let across = f64::from(w as f32) * sf / (f64::from(k) * 320.0);
                let down = f64::from(h as f32) * sf / (f64::from(k) * 240.0);
                assert!(
                    (across - down).abs() < 1e-5,
                    "sf {sf} k {k}: {across:.7} across and {down:.7} down is a stretch"
                );
            }
        }
        assert!(
            short.is_empty(),
            "{} of {} swept cases draw the panel short of its own framebuffer:\n  {}",
            short.len(),
            SF_SWEEP.len() * K_MAX as usize * 2,
            short.join("\n  ")
        );
    }

    /// The ratio arm of the same obligation, and §16.10 asks for it by name: **put the old pair
    /// back and watch it go red.**
    ///
    /// A sweep that can only fail on the f32 tail would pass forever if somebody re-measured the
    /// screen wrongly, because `panel_logical` does not read the ratios at all. This is the arm
    /// that does, and it is the shape `the_old_ratios_would_fail_this_test` uses: hand the checker
    /// the values that shipped and require it to reject them.
    #[test]
    fn the_old_ratios_would_draw_the_panel_off_its_own_framebuffer() {
        // What `ui/ipod.slint` draws: `Geometry.screen-w * body-height`.
        let drawn = |hero: f64, ratio: f64| hero * ratio;
        let (sw, sh) = (0.4866, 0.3672);
        let w = drawn(HERO_PHYS_1X, sw);
        let h = drawn(HERO_PHYS_1X, sh);
        assert!(
            (w - 320.0).abs() > 0.1 || (h - 240.0).abs() > 0.1,
            "the pre-§6.6 pair {sw} / {sh} drew {w:.4} × {h:.4} and this test did not notice"
        );
        assert!(
            ((w / 320.0) - (h / 240.0)).abs() > 1e-4,
            "the pre-§6.6 pair is supposed to be a stretch: {:.6} across, {:.6} down",
            w / 320.0,
            h / 240.0
        );
        // And the pair in force is not.
        let w = drawn(HERO_PHYS_1X, SCREEN_W);
        let h = drawn(HERO_PHYS_1X, SCREEN_H);
        assert!(
            (w - 320.0).abs() < 0.01 && (h - 240.0).abs() < 0.01,
            "the ratios in force draw {w:.4} × {h:.4} for a 320 × 240 framebuffer"
        );
    }

    /// §6.6's glass, and the two functions that would otherwise be constants nobody checks.
    ///
    /// This is §16.10's `the_glass_is_the_panel_plus_ten_and_a_half_physical_pixels`, at the level
    /// the model can assert it: the surround is the same on all four sides at every `k`, and the
    /// glass is the panel plus it rather than a ratio of the body.
    #[test]
    fn the_glass_is_the_panel_plus_ten_and_a_half_physical_pixels() {
        assert!(
            (bezel_phys() - 10.49).abs() < 0.01,
            "the bezel is {:.2} physical px; §6.1 declares 10.49 as a checkable invariant",
            bezel_phys()
        );
        for k in 1..=K_MAX {
            let (gw, gh) = glass_phys(k);
            let across = gw - f64::from(k) * 320.0;
            let down = gh - f64::from(k) * 240.0;
            assert!(
                (across - down).abs() < 1e-9,
                "at k={k} the glass leaves {across:.4} across and {down:.4} down; the surround is \
                 supposed to be the same on all four sides"
            );
            assert!(
                (across / 2.0 - bezel_phys()).abs() < 1e-9,
                "at k={k} the surround is {:.4} per side, not {:.4}",
                across / 2.0,
                bezel_phys()
            );
        }
        let (gw, gh) = glass_phys(1);
        assert!(
            (gw - 341.0).abs() < 0.1 && (gh - 261.0).abs() < 0.1,
            "the glass at k=1 is {gw:.1} × {gh:.1}; §6.6 says 341.0 × 261.0"
        );
    }

    /// Nothing in [`ALL`] can be defined and then silently not emitted.
    #[test]
    fn every_geometry_constant_reaches_the_markup() {
        for (name, unit, value) in ALL {
            let suffix = match unit {
                Unit::Ratio => "",
                Unit::Px => "px",
            };
            let want = format!(
                "    out property <{}> {}: {}{suffix};\n",
                match unit {
                    Unit::Ratio => "float",
                    Unit::Px => "length",
                },
                slint_name(name),
                slint_number(*value)
            );
            assert!(
                GENERATED.contains(&want),
                "{name} is declared and never emitted; the generated file has no line\n{want}"
            );
        }
    }

    /// The first pair of names that mangle to the same Slint property, if there is one.
    fn first_collision(names: &[&str]) -> Option<(String, String, String)> {
        let mut seen: Vec<(String, &str)> = Vec::new();
        for name in names {
            let slint = slint_name(name);
            if let Some((_, other)) = seen.iter().find(|(s, _)| *s == slint) {
                return Some((name.to_string(), other.to_string(), slint));
            }
            seen.push((slint, name));
        }
        None
    }

    /// The Rust → Slint mangling is injective, so a rename cannot make two constants collide into
    /// one Slint property with the later one silently winning.
    ///
    /// **Honest limitation, and it is why the control below is half the test.** A real collision in
    /// [`ALL`] cannot make this assertion fire, because the generated file would then declare the
    /// same property twice and `build.rs` fails first — the crate never compiles, so no test runs.
    /// What this buys over Slint's own duplicate-property error is a message that names the two
    /// **Rust** constants, which the slint compiler cannot know about. The control is what proves
    /// the detector works at all.
    ///
    /// (`SCREEN__W` is *not* an example of a collision: two underscores mangle to two hyphens.
    /// Names differing only in case are, which is why the control uses one.)
    #[test]
    fn no_two_constants_share_a_slint_name() {
        let names: Vec<&str> = ALL.iter().map(|(n, _, _)| *n).collect();
        if let Some((a, b, slint)) = first_collision(&names) {
            panic!("{a} and {b} both mangle to `{slint}`");
        }

        // The control (AGENTS.md §6): before believing that nothing collided, make it collide.
        let (a, b, slint) = first_collision(&["SCREEN_W", "BODY_ASPECT", "Screen_w"])
            .expect("the collision detector cannot see a collision it is handed");
        assert_eq!((a.as_str(), b.as_str(), slint.as_str()), ("Screen_w", "SCREEN_W", "screen-w"));
    }

    /// Every emitted value is a plain decimal.
    ///
    /// Slint's lexer reads the `e` of `1e-5` as a unit. Verified, not assumed — a constant of
    /// `1.0e-5` makes `build.rs` stop with
    /// `error: Invalid unit 'e'. Valid units are: %, phx, px, cm, mm, in, pt, rem, s, ms, deg,
    /// grad, turn, rad`, pointing at the generated file.
    ///
    /// **Like `no_two_constants_share_a_slint_name`, the first half cannot be made red on its own**:
    /// an offending constant trips [`slint_number`]'s assert inside the build script, and if that
    /// were removed the slint compiler trips on the emitted file — either way the crate never
    /// compiles and no test runs. So the second half is the control: it proves the guard is armed
    /// by handing it the value.
    #[test]
    fn the_generated_slint_carries_no_scientific_notation() {
        for line in slint_source().lines() {
            let Some((_, rest)) = line.split_once(": ") else {
                continue;
            };
            let token = rest.trim_end_matches(';');
            let body = token.strip_suffix("px").unwrap_or(token);
            assert!(
                !body.is_empty()
                    && body
                        .bytes()
                        .all(|b| b.is_ascii_digit() || b == b'.' || b == b'-'),
                "`{token}` is not a plain decimal; Slint reads the exponent as a unit"
            );
        }

        // The control (AGENTS.md §6). `1.0e-5` formats as `1e-5`, which is what Slint chokes on.
        assert_eq!(format!("{:?}", 1.0e-5_f64), "1e-5");
        let armed = std::panic::catch_unwind(|| slint_number(1.0e-5)).is_err();
        assert!(
            armed,
            "slint_number let `1e-5` through; the build script would emit it and Slint would \
             report `Invalid unit 'e'` from a generated file nobody edited"
        );
    }

    /// The generated file and the source of truth are the same bytes.
    ///
    /// If [`slint_source`] ever became non-deterministic, the write-if-changed guard in `build.rs`
    /// would rewrite `geometry.slint` on every run, `slint-build`'s own `rerun-if-changed` would
    /// see it newer than the fingerprint, and the crate would recompile on every `cargo build`
    /// forever — which reads as Slint being slow rather than as a bug.
    #[test]
    fn the_generated_file_is_byte_identical_to_the_source_of_truth() {
        assert_eq!(
            GENERATED,
            slint_source(),
            "the file in OUT_DIR is not what slint_source() produces"
        );
    }

    /// `ui/geometry.slint` must not exist on disk.
    ///
    /// Under the `@geometry` library arrangement such a file would be ignored — an import beginning
    /// `@` is resolved **only** through the library paths (`i-slint-compiler/typeloader.rs:1259`).
    /// This guards against a later maintainer switching to `with_include_paths`, whose first
    /// candidate directory is the importing file's own, at which point a stale `ui/geometry.slint`
    /// would silently win over the generated one.
    #[test]
    fn the_markup_imports_the_generated_global_and_nothing_shadows_it() {
        let shadow = std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/ui/geometry.slint"
        ));
        assert!(
            !shadow.exists(),
            "{} exists; the generated global must have no file of that name to shadow it",
            shadow.display()
        );
        for (name, text) in [("ui/ipod.slint", IPOD_SLINT), ("ui/window.slint", WINDOW_SLINT)] {
            assert!(
                text.contains("from \"@geometry\""),
                "{name} does not import the generated Geometry global"
            );
        }
    }

    /// §16.1's one-way arrow, mechanically.
    ///
    /// The window's own four size constants must not read `hero`. `preferred-height: root.hero +
    /// Geometry.chrome-pref` is arithmetically the truest thing anybody could write there and is
    /// exactly the trap — it closes the loop, and Slint reports the inherited case as a deprecation
    /// *warning* saying it may panic at run time, which is the weaker signal this test upgrades.
    #[test]
    fn the_window_constants_do_not_read_the_hero() {
        // **Every** size constant in the file, not only the window's four: the pane that holds the
        // device is pinned to `min-height: 0px; preferred-height: 0px` for the same reason (§16.1,
        // "the container must declare no intrinsic height"), and a `hero` in either place closes
        // the same loop one level down.
        let mut seen = 0;
        for line in WINDOW_SLINT.lines() {
            let t = line.trim();
            for prop in ["min-width:", "min-height:", "preferred-width:", "preferred-height:"] {
                if t.starts_with(prop) {
                    seen += 1;
                    assert!(
                        !t.contains("hero"),
                        "`{prop}` reads the body height, which closes the binding loop: {t}"
                    );
                }
            }
        }
        assert!(seen >= 4, "the window no longer declares its size constants");

        // And the window's own four are still bound to the generated constants rather than to
        // anything the layout can influence.
        for want in [
            "min-width: Geometry.min-width;",
            "min-height: Geometry.min-height;",
            "preferred-width: Geometry.pref-width;",
            "preferred-height: Geometry.pref-height;",
        ] {
            assert!(
                WINDOW_SLINT.lines().any(|l| l.trim() == want),
                "the window no longer declares `{want}`"
            );
        }
    }

    // ── The literal sweep, and the one exemption it carries ─────────────────────────────────────

    /// Properties whose value is a position, a size or a type measure.
    const GEOMETRY_PROPS: &[&str] = &[
        "x",
        "y",
        "width",
        "height",
        "min-width",
        "min-height",
        "preferred-width",
        "preferred-height",
        "border-radius",
        "font-size",
        "letter-spacing",
        "padding",
        "padding-left",
        "padding-right",
        "padding-top",
        "padding-bottom",
        "spacing",
        // `IPod`'s own size input. It is the one property in this markup whose value IS the body
        // height, and it was missing from this list — so `body-height: 655.751px` on a new use
        // site would have gone straight through the sweep that exists to stop exactly that.
        "body-height",
    ];

    /// Closed and exact. `0` and `0px` are nothing; `1px` is a device-pixel hairline, not a
    /// fraction of the body (`ipod.slint`'s two borders); `2` is the `/ 2` centring divisor;
    /// `100%` and `50%` are relative to the parent, which is what they are for; `420px` is
    /// `IPod`'s `body-height` **default**, which exists so `slint-viewer` and the live preview draw
    /// a plausible device with no Rust running — every real use site passes a size.
    const ALLOWED: &[&str] = &["0", "0px", "1px", "2", "100%", "50%", "420px"];

    /// **The exemption, enumerated line by line, with a retirement condition.**
    ///
    /// These are `window.slint`'s **control metrics** — a 36 px control, a 6 px radius, the 56 px
    /// chrome bar, the 60 px device row, the caption slots, the 7 px carousel dot. They are not
    /// geometry in §6.6's sense (a fraction of body height) and they are not §9.6's column; they
    /// belong to §6.2 and §6.3, whose single source of truth is `Metric` in `ui/tokens.slint`,
    /// which item 9 does not own.
    ///
    /// **Retirement condition**: §9.6 deletes the chrome bar and the caption stack outright, and
    /// §4 replaces the tab strip with the drawer. When the bench is rebuilt, every line below goes
    /// with it and this list becomes empty — at which point delete it rather than let it stand.
    ///
    /// Enumerated as whole lines rather than as bare values on purpose: a **new** `height: 36px` on
    /// a new element fails this test, which a value-only allowlist would wave through.
    const CONTROL_METRICS: &[&str] = &[
        "height: 36px;",                     // Button, Tab — one control height
        "border-radius: 6px;",               // Button, Tab, and each one's Material fill
        "height: 56px;",                     // the chrome bar §9.6 deletes
        "height: 60px;",                     // a device row on the Devices tab
        "height: 20px;",                     // a caption slot
        "height: 16px;",                     // the write-target line
        "height: 8px;",                      // the carousel dot row
        "width: 7px;",                       // a carousel dot
        "height: 7px;",
        "border-radius: 3.5px;",
        "spacing: 2px;",                     // the two-line device row
        "height: r.heading ? 44px : 30px;",  // a resource row, heading or not
    ];

    /// Strip string literals, then `//` comments, so neither can hide or invent a number.
    fn strip(line: &str) -> String {
        let mut out = String::new();
        let mut in_string = false;
        let mut chars = line.chars().peekable();
        while let Some(c) = chars.next() {
            match c {
                '"' => in_string = !in_string,
                '/' if !in_string && chars.peek() == Some(&'/') => break,
                _ if !in_string => out.push(c),
                _ => {}
            }
        }
        out
    }

    /// Every numeric literal in `text`, with its unit.
    ///
    /// Identifiers and colours are consumed **whole** first, because digits live inside both:
    /// `Metric.s7` is a name, `#ffffff14` is a colour, and — the one that actually bit —
    /// `Geometry.hero-phys-1x` is a name whose last two characters look exactly like a length. A
    /// hyphen is an identifier character in Slint, so scanning backwards one character is not
    /// enough to tell `hero-phys-1x` from `parent.height - 1px`.
    fn numbers(text: &str) -> Vec<String> {
        let b: Vec<char> = text.chars().collect();
        let mut out = Vec::new();
        let mut i = 0;
        while i < b.len() {
            let c = b[i];
            if c.is_alphabetic() || c == '_' {
                // An identifier: letters, digits, `_` and `-`, all the way to the end of it.
                while i < b.len() && (b[i].is_alphanumeric() || b[i] == '_' || b[i] == '-') {
                    i += 1;
                }
            } else if c == '#' {
                i += 1;
                while i < b.len() && b[i].is_alphanumeric() {
                    i += 1;
                }
            } else if c.is_ascii_digit() {
                let start = i;
                while i < b.len() && (b[i].is_ascii_digit() || b[i] == '.') {
                    i += 1;
                }
                while i < b.len() && (b[i].is_ascii_alphabetic() || b[i] == '%') {
                    i += 1;
                }
                out.push(b[start..i].iter().collect());
            } else {
                i += 1;
            }
        }
        out
    }

    /// Does this line assign to something whose value is a length or a position?
    fn is_geometry_line(t: &str) -> bool {
        // A `property <length> foo: …` declaration is geometry too — that is where `0.5917 * hero`
        // used to live.
        if t.starts_with("property <length>") || t.starts_with("in property <length>") {
            return true;
        }
        GEOMETRY_PROPS
            .iter()
            .any(|p| t.starts_with(p) && t[p.len()..].starts_with(':'))
    }

    /// The exemption list shrinks to nothing and then goes, rather than rotting in place.
    ///
    /// An allowlist entry that no longer matches any line is a bypass with nothing behind it —
    /// exactly the shape §16.9 deletes. This makes the list self-retiring: when the bench is
    /// rebuilt and the last chrome line goes, the entry that covered it fails here.
    #[test]
    fn every_exemption_still_covers_a_line() {
        let lines: Vec<&str> = WINDOW_SLINT.lines().map(str::trim).collect();
        for e in CONTROL_METRICS {
            assert!(
                lines.contains(e),
                "`{e}` is exempted and appears nowhere in ui/window.slint; delete the exemption"
            );
        }
    }

    /// **The hole this whole item exists to close.**
    ///
    /// After this test passes, editing the markup's geometry is not possible without editing
    /// `src/geometry.rs` — which is the mechanical form of "the test reads what the markup reads".
    ///
    /// **Whole statements, not lines.** A binding that wraps —
    ///
    /// ```text
    /// x: parent.width / 2 - self.width / 2
    ///  + (i - root.selected) * 88px;
    /// ```
    ///
    /// — puts its literal on a line that does not begin with a geometry property, so a per-line
    /// sweep never looks at it. Statements are joined to the `;` before they are swept.
    ///
    /// The exemption is scoped to `window.slint`, which is the file it was enumerated from and the
    /// only file `every_exemption_still_covers_a_line` checks it against. Applying it to
    /// `ipod.slint` as well would let a line silently escape in a file nothing verifies the list
    /// against — and `ipod.slint`, the drawn device, is what item 9 is actually about.
    #[test]
    fn no_geometry_literal_survives_in_the_markup() {
        for (file, text) in [("ui/ipod.slint", IPOD_SLINT), ("ui/window.slint", WINDOW_SLINT)] {
            let exempt: &[&str] = if file == "ui/window.slint" {
                CONTROL_METRICS
            } else {
                &[]
            };
            let lines: Vec<String> = text.lines().map(|l| strip(l).trim().to_string()).collect();
            for (n, first) in lines.iter().enumerate() {
                if !is_geometry_line(first) || exempt.contains(&first.as_str()) {
                    continue;
                }
                // Join to the end of the statement. A binding that opens a block (`=> {`) is not
                // one statement, so the join stops at a brace as well as at a semicolon.
                let mut stmt = first.clone();
                let mut at = n;
                while !stmt.contains(';') && !stmt.contains('{') && at + 1 < lines.len() {
                    at += 1;
                    stmt.push(' ');
                    stmt.push_str(&lines[at]);
                }
                for num in numbers(&stmt) {
                    assert!(
                        ALLOWED.contains(&num.as_str()),
                        "{file}:{}: `{num}` is a geometry literal; it belongs in \
                         src/geometry.rs\n  {stmt}",
                        n + 1
                    );
                }
            }
        }
    }

    /// **The control that makes the instrument produce a non-zero.**
    ///
    /// `AGENTS.md` §6: before believing a zero, run the control. The sweep above reports nothing,
    /// and a sweep that reports nothing because its matcher is broken looks exactly the same. This
    /// feeds it the two lines that used to be in the markup and asserts they are caught.
    #[test]
    fn the_literal_sweep_can_see_a_literal() {
        assert!(is_geometry_line("width: 0.5917 * h;"));
        assert!(is_geometry_line("property <length> hero: 655.751px;"));
        assert!(!is_geometry_line("background: #08080a;"));
        // `body-height` is the drawing's own size input, and it was not in the list.
        assert!(is_geometry_line("body-height: 655.751px;"));
        // A property whose name merely *starts* with one of them is not one of them.
        assert!(!is_geometry_line("heightish: 12px;"));

        let caught: Vec<String> = numbers(&strip("width: 0.5917 * h; // 0.4866 was wrong"))
            .into_iter()
            .filter(|n| !ALLOWED.contains(&n.as_str()))
            .collect();
        assert_eq!(
            caught,
            vec!["0.5917".to_string()],
            "the sweep would not have caught the ratio that used to be written here"
        );

        // `Metric.s7` is a name, not a 7; `#ffffff14` is a colour, not a 14; and
        // `Geometry.hero-phys-1x` is a name, not a `1x` — which the first version of this scanner
        // read as a literal, because a hyphen is an identifier character in Slint.
        assert!(numbers("spacing: Metric.s7;").is_empty());
        assert!(numbers("border-color: #ffffff14;").is_empty());
        assert!(numbers("border-color: #08080a;").is_empty());
        assert!(numbers("in property <length> hero: Geometry.hero-phys-1x;").is_empty());
        // …but a real subtraction of a real length still reads as one.
        assert_eq!(numbers("y: parent.height - 1px;"), vec!["1px"]);
        // …and the allowlist really is consulted rather than everything being waved through.
        assert_eq!(numbers("y: (parent.height - self.height) / 2;"), vec!["2"]);
    }
}
